name: Build CS2 Enemy Coordinates

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Compile with MSVC
      run: |
        cl /EHsc /std:c++17 cs2_enemy_coordinates.cpp /link /out:cs2_enemy_coordinates.exe
      shell: cmd

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: cs2_enemy_coordinates
        path: cs2_enemy_coordinates.exe
