name: Build Demo and External Reader

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Compile demo_game.cpp
        run: |
          cl /EHsc /std:c++17 demo_game.cpp /link user32.lib kernel32.lib
        shell: cmd

      - name: Compile external_reader.cpp
        run: |
          cl /EHsc /std:c++17 external_reader.cpp /link user32.lib kernel32.lib
        shell: cmd

      - name: List binaries
        run: dir
        shell: cmd

      - name: Upload demo_game artifact
        uses: actions/upload-artifact@v4
        with:
          name: demo_game
          path: demo_game.exe

      - name: Upload external_reader artifact
        uses: actions/upload-artifact@v4
        with:
          name: external_reader
          path: external_reader.exe
